exp_name: fbauto_v1_hypergraph
dataset_name: FB-AUTO

# ===============================
# Dataset paths
# ===============================
train_path: data/FB-AUTO/train/train_2.txt
valid_path: data/FB-AUTO/valid/valid_2.txt
test_graph: data/FB-AUTO/test/test_2.txt

# ===============================
# Graph construction
# ===============================
add_2hop: true

# ===============================
# Learning parameters
# ===============================
learning_rate: 0.001
weight_decay: 1e-5
dropout: 0.2
num_layers: 2
num_epochs: 2000
bce_weight: 5.0
lr_gamma: 0.99            # ✅ 新增（学习率衰减系数，默认为 0.99）
early_stop_patience: 200  # ✅ 新增（早停上限）
log_every: 50             # ✅ 新增（打印间隔）
num_neg_eval: 50


# ===============================
# Thresholds
# ===============================
threshold: 0.5
threshold_a: 0.1
threshold_b: 0.3
sc_threshold: 0.5

# ===============================
# Rule guidance
# ===============================
add_rules: true
rule_weight: 0.1
rule_file_path: rules/FB-AUTO_rules.txt

# ===============================
# Constraints
# ===============================
add_constraints: true
add_mask: true

