exp_name: jf17k_v4_rules
dataset_name: JF17K-4

# ===============================
# Dataset paths
# ===============================
train_path: data/JF17K-4/train/train.txt
valid_path: data/JF17K-4/valid/valid.txt
test_graph: data/JF17K-4/test/test.txt

# ===============================
# Graph construction
# ===============================
add_2hop: true

# ===============================
# Learning parameters
# ===============================
learning_rate: 0.003
weight_decay: 0.0
dropout: 0.1
num_layers: 3
num_epochs: 1500
bce_weight: 5.0
lr_gamma: 0.99
early_stop_patience: 200
log_every: 50
num_neg_eval: 50

# ===============================
# Thresholds
# ===============================
threshold: 0.5
threshold_a: 0.1
threshold_b: 0.7
sc_threshold: 0.5

# ===============================
# Rule guidance
# ===============================
add_rules: true
rule_weight: 1.0
rule_file_path: data/JF17K-4_rules.txt

# ===============================
# Constraints
# ===============================
add_constraints: true
add_mask: true
